# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Mon Apr 29 21:35:00 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(684, 437)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.arvoreMeses = QtGui.QTreeView(self.centralwidget)
        self.arvoreMeses.setGeometry(QtCore.QRect(5, 5, 156, 356))
        self.arvoreMeses.setObjectName("arvoreMeses")
        self.tabelaHorario = QtGui.QTableWidget(self.centralwidget)
        self.tabelaHorario.setGeometry(QtCore.QRect(170, 65, 506, 211))
        self.tabelaHorario.setObjectName("tabelaHorario")
        self.tabelaHorario.setColumnCount(0)
        self.tabelaHorario.setRowCount(0)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(170, 5, 506, 51))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtGui.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(5, 10, 114, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtGui.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 10, 114, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtGui.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 10, 114, 32))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtGui.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(380, 10, 114, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 285, 506, 76))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(35, 15, 171, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(35, 40, 171, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(240, 40, 146, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(240, 15, 216, 16))
        self.label_4.setObjectName("label_4")
        mainWindow.setCentralWidget(self.centralwidget)
        self.mainMenuBar = QtGui.QMenuBar()
        self.mainMenuBar.setGeometry(QtCore.QRect(0, 0, 684, 22))
        self.mainMenuBar.setObjectName("mainMenuBar")
        self.menuArquivo = QtGui.QMenu(self.mainMenuBar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuEditar = QtGui.QMenu(self.mainMenuBar)
        self.menuEditar.setObjectName("menuEditar")
        self.menuAjuda = QtGui.QMenu(self.mainMenuBar)
        self.menuAjuda.setObjectName("menuAjuda")
        mainWindow.setMenuBar(self.mainMenuBar)
        self.mainStatusBar = QtGui.QStatusBar(mainWindow)
        self.mainStatusBar.setObjectName("mainStatusBar")
        mainWindow.setStatusBar(self.mainStatusBar)
        self.mainToolBar = QtGui.QToolBar(mainWindow)
        self.mainToolBar.setMovable(False)
        self.mainToolBar.setObjectName("mainToolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actionAbrir = QtGui.QAction(mainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionSair = QtGui.QAction(mainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionConfiguracoes = QtGui.QAction(mainWindow)
        self.actionConfiguracoes.setObjectName("actionConfiguracoes")
        self.actionSobre = QtGui.QAction(mainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSair)
        self.menuEditar.addAction(self.actionConfiguracoes)
        self.menuAjuda.addAction(self.actionSobre)
        self.mainMenuBar.addAction(self.menuArquivo.menuAction())
        self.mainMenuBar.addAction(self.menuEditar.menuAction())
        self.mainMenuBar.addAction(self.menuAjuda.menuAction())
        self.mainToolBar.addAction(self.actionAbrir)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionConfiguracoes)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.arvoreMeses, self.pushButton)
        mainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        mainWindow.setTabOrder(self.pushButton_2, self.pushButton_3)
        mainWindow.setTabOrder(self.pushButton_3, self.pushButton_4)
        mainWindow.setTabOrder(self.pushButton_4, self.tabelaHorario)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "PyHE - Controle de Horas Extras", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("mainWindow", "Marca ponto", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_2.setText(QtGui.QApplication.translate("mainWindow", "Adicionar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("mainWindow", "Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("mainWindow", "Excluir", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mainWindow", "Horas positivas: 00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mainWindow", "Horas negativas: 00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("mainWindow", "Total de horas: 00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("mainWindow", "Horas para compensação: 00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArquivo.setTitle(QtGui.QApplication.translate("mainWindow", "Arquivo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEditar.setTitle(QtGui.QApplication.translate("mainWindow", "Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAjuda.setTitle(QtGui.QApplication.translate("mainWindow", "Ajuda", None, QtGui.QApplication.UnicodeUTF8))
        self.mainToolBar.setWindowTitle(QtGui.QApplication.translate("mainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir.setText(QtGui.QApplication.translate("mainWindow", "Abrir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSair.setText(QtGui.QApplication.translate("mainWindow", "Sair", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfiguracoes.setText(QtGui.QApplication.translate("mainWindow", "Configurações", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSobre.setText(QtGui.QApplication.translate("mainWindow", "Sobre", None, QtGui.QApplication.UnicodeUTF8))

