# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow-0.02.ui'
#
# Created: Fri May  3 22:56:48 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(670, 540)
        mainWindow.setMinimumSize(QtCore.QSize(670, 540))
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.arvoreMeses = QtGui.QTreeView(self.centralwidget)
        self.arvoreMeses.setMaximumSize(QtCore.QSize(150, 16777215))
        self.arvoreMeses.setObjectName("arvoreMeses")
        self.gridLayout_2.addWidget(self.arvoreMeses, 0, 0, 2, 1)
        self.tabelaHorario = QtGui.QTableWidget(self.centralwidget)
        self.tabelaHorario.setObjectName("tabelaHorario")
        self.tabelaHorario.setColumnCount(6)
        self.tabelaHorario.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tabelaHorario.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tabelaHorario.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tabelaHorario.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tabelaHorario.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tabelaHorario.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tabelaHorario.setHorizontalHeaderItem(5, item)
        self.tabelaHorario.horizontalHeader().setDefaultSectionSize(75)
        self.tabelaHorario.horizontalHeader().setStretchLastSection(True)
        self.tabelaHorario.verticalHeader().setStretchLastSection(False)
        self.gridLayout_2.addWidget(self.tabelaHorario, 0, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 70))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 1, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.mainMenuBar = QtGui.QMenuBar()
        self.mainMenuBar.setGeometry(QtCore.QRect(0, 0, 670, 22))
        self.mainMenuBar.setObjectName("mainMenuBar")
        self.menuArquivo = QtGui.QMenu(self.mainMenuBar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuEditar = QtGui.QMenu(self.mainMenuBar)
        self.menuEditar.setObjectName("menuEditar")
        self.menuAjuda = QtGui.QMenu(self.mainMenuBar)
        self.menuAjuda.setObjectName("menuAjuda")
        self.menuPonto = QtGui.QMenu(self.mainMenuBar)
        self.menuPonto.setObjectName("menuPonto")
        self.menuRelat_rios = QtGui.QMenu(self.mainMenuBar)
        self.menuRelat_rios.setObjectName("menuRelat_rios")
        mainWindow.setMenuBar(self.mainMenuBar)
        self.mainStatusBar = QtGui.QStatusBar(mainWindow)
        self.mainStatusBar.setObjectName("mainStatusBar")
        mainWindow.setStatusBar(self.mainStatusBar)
        self.mainToolBar = QtGui.QToolBar(mainWindow)
        self.mainToolBar.setMovable(False)
        self.mainToolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.mainToolBar.setObjectName("mainToolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actionAbrir = QtGui.QAction(mainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/glyphicons_144_folder_open@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbrir.setIcon(icon)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionSair = QtGui.QAction(mainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/glyphicons_063_power@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSair.setIcon(icon1)
        self.actionSair.setObjectName("actionSair")
        self.actionConfiguracoes = QtGui.QAction(mainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/glyphicons_023_cogwheels@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConfiguracoes.setIcon(icon2)
        self.actionConfiguracoes.setObjectName("actionConfiguracoes")
        self.actionSobre = QtGui.QAction(mainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/glyphicons_195_circle_info@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSobre.setIcon(icon3)
        self.actionSobre.setObjectName("actionSobre")
        self.actionMarcaPonto = QtGui.QAction(mainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/glyphicons_323_cartao-de-ponto@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMarcaPonto.setIcon(icon4)
        self.actionMarcaPonto.setObjectName("actionMarcaPonto")
        self.actionAdicionarHorarios = QtGui.QAction(mainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/glyphicons_090_custom-table-plus@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdicionarHorarios.setIcon(icon5)
        self.actionAdicionarHorarios.setObjectName("actionAdicionarHorarios")
        self.actionEditarHorarios = QtGui.QAction(mainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/glyphicons_090_custom-table-edit@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionEditarHorarios.setIcon(icon6)
        self.actionEditarHorarios.setObjectName("actionEditarHorarios")
        self.actionExcluirHorarios = QtGui.QAction(mainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/glyphicons_090_custom-table-minus@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExcluirHorarios.setIcon(icon7)
        self.actionExcluirHorarios.setObjectName("actionExcluirHorarios")
        self.actionImportarHorarios = QtGui.QAction(mainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/glyphicons_358_file_import@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionImportarHorarios.setIcon(icon8)
        self.actionImportarHorarios.setObjectName("actionImportarHorarios")
        self.actionRelatorioMes = QtGui.QAction(mainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/glyphicons_040_stats@2x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRelatorioMes.setIcon(icon9)
        self.actionRelatorioMes.setObjectName("actionRelatorioMes")
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSair)
        self.menuEditar.addAction(self.actionConfiguracoes)
        self.menuAjuda.addAction(self.actionSobre)
        self.menuPonto.addAction(self.actionMarcaPonto)
        self.menuPonto.addSeparator()
        self.menuPonto.addAction(self.actionAdicionarHorarios)
        self.menuPonto.addAction(self.actionEditarHorarios)
        self.menuPonto.addAction(self.actionExcluirHorarios)
        self.menuPonto.addSeparator()
        self.menuPonto.addAction(self.actionImportarHorarios)
        self.menuRelat_rios.addAction(self.actionRelatorioMes)
        self.mainMenuBar.addAction(self.menuArquivo.menuAction())
        self.mainMenuBar.addAction(self.menuPonto.menuAction())
        self.mainMenuBar.addAction(self.menuRelat_rios.menuAction())
        self.mainMenuBar.addAction(self.menuEditar.menuAction())
        self.mainMenuBar.addAction(self.menuAjuda.menuAction())
        self.mainToolBar.addAction(self.actionAbrir)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMarcaPonto)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionAdicionarHorarios)
        self.mainToolBar.addAction(self.actionEditarHorarios)
        self.mainToolBar.addAction(self.actionExcluirHorarios)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionConfiguracoes)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.arvoreMeses, self.tabelaHorario)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "PyHE - Controle de Horas Extras", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelaHorario.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("mainWindow", "Dia", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelaHorario.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("mainWindow", "Entrada", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelaHorario.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("mainWindow", "Saída", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelaHorario.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("mainWindow", "Entrada", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelaHorario.horizontalHeaderItem(4).setText(QtGui.QApplication.translate("mainWindow", "Saída", None, QtGui.QApplication.UnicodeUTF8))
        self.tabelaHorario.horizontalHeaderItem(5).setText(QtGui.QApplication.translate("mainWindow", "Status", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mainWindow", "Horas negativas: 00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("mainWindow", "Total de horas: 00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("mainWindow", "Horas para compensação: 00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mainWindow", "Horas positivas: 00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArquivo.setTitle(QtGui.QApplication.translate("mainWindow", "Arquivo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEditar.setTitle(QtGui.QApplication.translate("mainWindow", "Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAjuda.setTitle(QtGui.QApplication.translate("mainWindow", "Ajuda", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPonto.setTitle(QtGui.QApplication.translate("mainWindow", "Ponto", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRelat_rios.setTitle(QtGui.QApplication.translate("mainWindow", "Relatórios", None, QtGui.QApplication.UnicodeUTF8))
        self.mainToolBar.setWindowTitle(QtGui.QApplication.translate("mainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir.setText(QtGui.QApplication.translate("mainWindow", "Abrir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSair.setText(QtGui.QApplication.translate("mainWindow", "Sair", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSair.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfiguracoes.setText(QtGui.QApplication.translate("mainWindow", "Configurações", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfiguracoes.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+,", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSobre.setText(QtGui.QApplication.translate("mainWindow", "Sobre", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMarcaPonto.setText(QtGui.QApplication.translate("mainWindow", "Marca ponto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMarcaPonto.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdicionarHorarios.setText(QtGui.QApplication.translate("mainWindow", "Adicionar horários", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdicionarHorarios.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditarHorarios.setText(QtGui.QApplication.translate("mainWindow", "Editar horários", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditarHorarios.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+Shift+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExcluirHorarios.setText(QtGui.QApplication.translate("mainWindow", "Excluir horários", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExcluirHorarios.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+Shift+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportarHorarios.setText(QtGui.QApplication.translate("mainWindow", "Importar horários", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRelatorioMes.setText(QtGui.QApplication.translate("mainWindow", "Relatório do mês", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
