# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow-0.02.ui'
#
# Created: Thu May  2 02:51:09 2013
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(684, 437)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.arvoreMeses = QtGui.QTreeView(self.centralwidget)
        self.arvoreMeses.setGeometry(QtCore.QRect(5, 5, 156, 356))
        self.arvoreMeses.setObjectName("arvoreMeses")
        self.tabelaHorario = QtGui.QTableWidget(self.centralwidget)
        self.tabelaHorario.setGeometry(QtCore.QRect(170, 5, 506, 271))
        self.tabelaHorario.setObjectName("tabelaHorario")
        self.tabelaHorario.setColumnCount(0)
        self.tabelaHorario.setRowCount(0)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(170, 285, 506, 76))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(35, 15, 171, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(35, 40, 171, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(240, 40, 146, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(240, 15, 216, 16))
        self.label_4.setObjectName("label_4")
        mainWindow.setCentralWidget(self.centralwidget)
        self.mainMenuBar = QtGui.QMenuBar()
        self.mainMenuBar.setGeometry(QtCore.QRect(0, 0, 684, 22))
        self.mainMenuBar.setObjectName("mainMenuBar")
        self.menuArquivo = QtGui.QMenu(self.mainMenuBar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuEditar = QtGui.QMenu(self.mainMenuBar)
        self.menuEditar.setObjectName("menuEditar")
        self.menuAjuda = QtGui.QMenu(self.mainMenuBar)
        self.menuAjuda.setObjectName("menuAjuda")
        self.menuPonto = QtGui.QMenu(self.mainMenuBar)
        self.menuPonto.setObjectName("menuPonto")
        self.menuRelat_rios = QtGui.QMenu(self.mainMenuBar)
        self.menuRelat_rios.setObjectName("menuRelat_rios")
        mainWindow.setMenuBar(self.mainMenuBar)
        self.mainStatusBar = QtGui.QStatusBar(mainWindow)
        self.mainStatusBar.setObjectName("mainStatusBar")
        mainWindow.setStatusBar(self.mainStatusBar)
        self.mainToolBar = QtGui.QToolBar(mainWindow)
        self.mainToolBar.setMovable(False)
        self.mainToolBar.setObjectName("mainToolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actionAbrir = QtGui.QAction(mainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionSair = QtGui.QAction(mainWindow)
        self.actionSair.setObjectName("actionSair")
        self.actionConfiguracoes = QtGui.QAction(mainWindow)
        self.actionConfiguracoes.setObjectName("actionConfiguracoes")
        self.actionSobre = QtGui.QAction(mainWindow)
        self.actionSobre.setObjectName("actionSobre")
        self.actionMarcaPonto = QtGui.QAction(mainWindow)
        self.actionMarcaPonto.setObjectName("actionMarcaPonto")
        self.actionAdicionarHorarios = QtGui.QAction(mainWindow)
        self.actionAdicionarHorarios.setObjectName("actionAdicionarHorarios")
        self.actionEditarHorarios = QtGui.QAction(mainWindow)
        self.actionEditarHorarios.setObjectName("actionEditarHorarios")
        self.actionExcluirHorarios = QtGui.QAction(mainWindow)
        self.actionExcluirHorarios.setObjectName("actionExcluirHorarios")
        self.actionImportarHorarios = QtGui.QAction(mainWindow)
        self.actionImportarHorarios.setObjectName("actionImportarHorarios")
        self.actionRelatorioMes = QtGui.QAction(mainWindow)
        self.actionRelatorioMes.setObjectName("actionRelatorioMes")
        self.menuArquivo.addAction(self.actionAbrir)
        self.menuArquivo.addSeparator()
        self.menuArquivo.addAction(self.actionSair)
        self.menuEditar.addAction(self.actionConfiguracoes)
        self.menuAjuda.addAction(self.actionSobre)
        self.menuPonto.addAction(self.actionMarcaPonto)
        self.menuPonto.addSeparator()
        self.menuPonto.addAction(self.actionAdicionarHorarios)
        self.menuPonto.addAction(self.actionEditarHorarios)
        self.menuPonto.addAction(self.actionExcluirHorarios)
        self.menuPonto.addSeparator()
        self.menuPonto.addAction(self.actionImportarHorarios)
        self.menuRelat_rios.addAction(self.actionRelatorioMes)
        self.mainMenuBar.addAction(self.menuArquivo.menuAction())
        self.mainMenuBar.addAction(self.menuPonto.menuAction())
        self.mainMenuBar.addAction(self.menuRelat_rios.menuAction())
        self.mainMenuBar.addAction(self.menuEditar.menuAction())
        self.mainMenuBar.addAction(self.menuAjuda.menuAction())
        self.mainToolBar.addAction(self.actionAbrir)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionMarcaPonto)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionAdicionarHorarios)
        self.mainToolBar.addAction(self.actionEditarHorarios)
        self.mainToolBar.addAction(self.actionExcluirHorarios)
        self.mainToolBar.addSeparator()
        self.mainToolBar.addAction(self.actionConfiguracoes)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.arvoreMeses, self.tabelaHorario)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "PyHE - Controle de Horas Extras", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mainWindow", "Horas positivas: 00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mainWindow", "Horas negativas: 00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("mainWindow", "Total de horas: 00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("mainWindow", "Horas para compensação: 00:00", None, QtGui.QApplication.UnicodeUTF8))
        self.menuArquivo.setTitle(QtGui.QApplication.translate("mainWindow", "Arquivo", None, QtGui.QApplication.UnicodeUTF8))
        self.menuEditar.setTitle(QtGui.QApplication.translate("mainWindow", "Editar", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAjuda.setTitle(QtGui.QApplication.translate("mainWindow", "Ajuda", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPonto.setTitle(QtGui.QApplication.translate("mainWindow", "Ponto", None, QtGui.QApplication.UnicodeUTF8))
        self.menuRelat_rios.setTitle(QtGui.QApplication.translate("mainWindow", "Relatórios", None, QtGui.QApplication.UnicodeUTF8))
        self.mainToolBar.setWindowTitle(QtGui.QApplication.translate("mainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir.setText(QtGui.QApplication.translate("mainWindow", "Abrir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbrir.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSair.setText(QtGui.QApplication.translate("mainWindow", "Sair", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSair.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfiguracoes.setText(QtGui.QApplication.translate("mainWindow", "Configurações", None, QtGui.QApplication.UnicodeUTF8))
        self.actionConfiguracoes.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+,", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSobre.setText(QtGui.QApplication.translate("mainWindow", "Sobre", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMarcaPonto.setText(QtGui.QApplication.translate("mainWindow", "Marca ponto", None, QtGui.QApplication.UnicodeUTF8))
        self.actionMarcaPonto.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdicionarHorarios.setText(QtGui.QApplication.translate("mainWindow", "Adicionar horários", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAdicionarHorarios.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditarHorarios.setText(QtGui.QApplication.translate("mainWindow", "Editar horários", None, QtGui.QApplication.UnicodeUTF8))
        self.actionEditarHorarios.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+Shift+H", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExcluirHorarios.setText(QtGui.QApplication.translate("mainWindow", "Excluir horários", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExcluirHorarios.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+Shift+X", None, QtGui.QApplication.UnicodeUTF8))
        self.actionImportarHorarios.setText(QtGui.QApplication.translate("mainWindow", "Importar horários", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRelatorioMes.setText(QtGui.QApplication.translate("mainWindow", "Relatório do mês", None, QtGui.QApplication.UnicodeUTF8))

